---
title: "Assignment 6"
format: html
editor: visual
---

# Question 1

a)  Using JSON YouTube: YouTube uses JSON to deliver video metadata, comments, and user interactions through its API. The JSON structure is hierarchical and includes nested fields for video IDs, thumbnails, and statistics such as views and likes. YouTube’s backend likely uses BigQuery and other Google Cloud services to store and manage data. The API fetches this data in JSON format, commonly consumed by frontend JavaScript frameworks.

b)  Using XML W3Schools: W3Schools offers XML data examples, including a sample file that provides information on books. The XML structure uses descriptive tags such as <book>, <author>, and <price>. The data can be accessed using XML parsers in JavaScript or server-side languages. Technologies like DOM and XSLT are used to query or transform the XML structure for web display.

# Question 2

i)  

``` sql
SELECT student.ID
FROM student
LEFT JOIN advisor ON student.ID = advisor.s_ID
WHERE advisor.i_ID IS NULL;
```

ii) 

``` sql
SELECT I.ID, I.name
FROM instructor I
WHERE NOT EXISTS (
  SELECT *
  FROM course C
  WHERE C.dept_name = I.dept_name
    AND NOT EXISTS (
      SELECT *
      FROM teaches T
      WHERE T.ID = I.ID AND T.course_id = C.course_id
    )
)
ORDER BY I.name;
```

# Question 3

a)  

``` r

   id     name              dept_name      salary
1  63395  McKinnon          Cybernetics    94333.99
2  78699  Pingr             Statistics     59303.62
3  96895  Mird              Marketing      119921.41
4  4233   Luo               English        88791.45
5  4034   Murata            Athletics      61387.56
6  50885  Konstantinides    Languages      32570.50
```

b)  

``` r
   id     name              dept_name      salary
1  63395  McKinnon          Cybernetics    94333.99
2  78699  Pingr             Statistics     59303.62
3  96895  Mird              Marketing      119921.41
4  4233   Luo               English        88791.45
5  4034   Murata            Athletics      61387.56
6  50885  Konstantinides    Languages      32570.50
```

c)  

``` r
    id       name           dept_name       tot_cred
1   79352    Rumat          Finance          100
2   76672    Miliko         Statistics       116
3   14182    Moszkowski     Civil Eng.       73
4   44985    Prieto         Biology          91
5   44271    Sowerby        English          108
6   40897    Coppens        Math             58
```

d)  

``` r
   id       name           dept_name        salary
1  63395    McKinnon       Cybernetics      94333.99
2  78699    Pingr          Statistics       59303.62
3  96895    Mird           Marketing        119921.41
4  4233     Luo            English          88791.45
5  4034     Murata         Athletics        61387.56
6  50885    Konstantinides Languages        32570.50
7  79653    Levine         Elec. Eng.       89805.83
8  50330    Shuming        Physics          108011.81
9  80759    Queiroz        Biology          45538.32
10 73623    Sullivan       Elec. Eng.       90038.09
11 97302    Bertolino      Mech. Eng.       51647.57
12 57180    Hau            Accounting       43966.29
13 74420    Voronina       Physics          121141.99
14 35579    Soisalon-...   Psychology       62579.61
15 31955    Moreira        Accounting       71351.42
16 37687    Arias          Statistics       104563.38
17 6569     Mingoz         Finance          105311.38
18 16807    Yazdi          Athletics        98333.65
19 14365    Lembr          Accounting       32241.56
20 90643    Choll          Statistics       57807.09
21 81991    Valtchev       Biology          77036.18
22 95030    Arinb          Statistics       54805.11
23 15347    Bawa           Athletics        72140.88
24 74426    Kenje          Marketing        106554.73
25 42782    Vicentino      Elec. Eng.       34272.67
26 58558    Dusserre       Marketing        66143.25
27 63287    Jaekel         Athletics        103146.87
28 59795    Desyl          Languages        48803.38
29 22591    DAgostino      Psychology       59706.49
30 48570    Sarkar         Pol. Sci.        87549.80
31 79081    Ullman         Accounting       47307.10
32 52647    Bancilhon      Pol. Sci.        87958.01
33 25946    Liley          Languages        90891.69
34 36897    Morris         Marketing        43770.36
35 72553    Yin            English          46397.59
36 3199     Gustafsson     Elec. Eng.       82534.37
37 34175    Bondi          Comp. Sci.       115469.11
38 48507    Lent           Mech. Eng.       107978.47
39 65931    Pimenta        Cybernetics      79866.95
40 3335     Bourrier       Comp. Sci.       80797.83
41 64871    Gutierrez      Statistics       45310.53
42 95709    Sakurai        English          118143.98
43 43779    Romero         Astronomy        79070.08
44 77346    Mahmoud        Geology          99382.59
45 28097    Kean           English          35023.18
46 90376    Bietzk         Cybernetics      117836.50
47 28400    Atanassov      Statistics       84982.92
48 41930    Tung           Athletics        50482.03
49 19368    Wieland        Pol. Sci.        124651.41
50 99052    Dale           Cybernetics      93348.83
```
